TOPICS:
___Manipulação do DOM (Document Object Model)
___Event Listeners
___Condicionais e Loops
___Funções
___Manipulação de Estilos CSS
___Temporizadores (Timers)
___Promessas e Assincronicidade
___Variáveis e Escopo
___Eventos e Manipulação de Elementos HTML
